### ADD

POST http://localhost:8080/urheilukauppa-backend/addProduct.php

{
    "productname": "strapsit", 
    "categoryid": "2", 
    "price": "15", 
    "sale": "", 
    "imgURL": "", 
    "descript": "hiento strapsit"
}